licenses(["notice"])

cc_binary(
    name = "BuildFullBinaryTree",
    srcs = ["full_binary.cc"],
    deps = [
        "@gbbs//gbbs",
    ],
)

package(
    default_visibility = ["//visibility:public"],
)
